// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using quizsergipe_api.Data;

#nullable disable

namespace quizsergipe_api.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("quizsergipe_api.Models.Alternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaId");

                    b.ToTable("Alternativas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 1,
                            Texto = "Reisado"
                        },
                        new
                        {
                            Id = 2,
                            Correta = false,
                            Letra = "B",
                            PerguntaId = 1,
                            Texto = "Bacamarteiros"
                        },
                        new
                        {
                            Id = 3,
                            Correta = true,
                            Letra = "C",
                            PerguntaId = 1,
                            Texto = "Lambe-Sujos"
                        },
                        new
                        {
                            Id = 4,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 1,
                            Texto = "Caboclinhos"
                        },
                        new
                        {
                            Id = 5,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 2,
                            Texto = "Maria Bonita"
                        },
                        new
                        {
                            Id = 6,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 2,
                            Texto = "Maria Feliciana"
                        },
                        new
                        {
                            Id = 7,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 2,
                            Texto = "Clemilda"
                        },
                        new
                        {
                            Id = 8,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 2,
                            Texto = "Dona Suja"
                        },
                        new
                        {
                            Id = 9,
                            Correta = true,
                            Letra = "A",
                            PerguntaId = 3,
                            Texto = "Zé Peixe"
                        },
                        new
                        {
                            Id = 10,
                            Correta = false,
                            Letra = "B",
                            PerguntaId = 3,
                            Texto = "Mateus"
                        },
                        new
                        {
                            Id = 11,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 3,
                            Texto = "Lampião"
                        },
                        new
                        {
                            Id = 12,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 3,
                            Texto = "Pedro Bombacho"
                        },
                        new
                        {
                            Id = 13,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 4,
                            Texto = "Bacamarte"
                        },
                        new
                        {
                            Id = 14,
                            Correta = false,
                            Letra = "B",
                            PerguntaId = 4,
                            Texto = "Buscapé"
                        },
                        new
                        {
                            Id = 15,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 4,
                            Texto = "Espada"
                        },
                        new
                        {
                            Id = 16,
                            Correta = true,
                            Letra = "D",
                            PerguntaId = 4,
                            Texto = "Barco de Fogo"
                        },
                        new
                        {
                            Id = 17,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 5,
                            Texto = "Terra da Luz"
                        },
                        new
                        {
                            Id = 18,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 5,
                            Texto = "País do Forró"
                        },
                        new
                        {
                            Id = 19,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 5,
                            Texto = "Capital do Caju"
                        },
                        new
                        {
                            Id = 20,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 5,
                            Texto = "Cidade Sorriso"
                        },
                        new
                        {
                            Id = 21,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 6,
                            Texto = "Siri"
                        },
                        new
                        {
                            Id = 22,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 6,
                            Texto = "Caranguejo"
                        },
                        new
                        {
                            Id = 23,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 6,
                            Texto = "Camarão"
                        },
                        new
                        {
                            Id = 24,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 6,
                            Texto = "Lagosta"
                        },
                        new
                        {
                            Id = 25,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 7,
                            Texto = "Mangaba"
                        },
                        new
                        {
                            Id = 26,
                            Correta = false,
                            Letra = "B",
                            PerguntaId = 7,
                            Texto = "Manga"
                        },
                        new
                        {
                            Id = 27,
                            Correta = true,
                            Letra = "C",
                            PerguntaId = 7,
                            Texto = "Caju"
                        },
                        new
                        {
                            Id = 28,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 7,
                            Texto = "Umbu"
                        },
                        new
                        {
                            Id = 29,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 8,
                            Texto = "Laranjeiras"
                        },
                        new
                        {
                            Id = 30,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 8,
                            Texto = "São Cristóvão"
                        },
                        new
                        {
                            Id = 31,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 8,
                            Texto = "Itabaiana"
                        },
                        new
                        {
                            Id = 32,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 8,
                            Texto = "Estância"
                        },
                        new
                        {
                            Id = 33,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 9,
                            Texto = "Cabanagem"
                        },
                        new
                        {
                            Id = 34,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 9,
                            Texto = "Cangaço"
                        },
                        new
                        {
                            Id = 35,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 9,
                            Texto = "Revolta da Chibata"
                        },
                        new
                        {
                            Id = 36,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 9,
                            Texto = "Messianismo"
                        },
                        new
                        {
                            Id = 37,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 10,
                            Texto = "Guerreiro"
                        },
                        new
                        {
                            Id = 38,
                            Correta = false,
                            Letra = "B",
                            PerguntaId = 10,
                            Texto = "Reisado"
                        },
                        new
                        {
                            Id = 39,
                            Correta = true,
                            Letra = "C",
                            PerguntaId = 10,
                            Texto = "Bacamarteiros"
                        },
                        new
                        {
                            Id = 40,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 10,
                            Texto = "Parafusos"
                        },
                        new
                        {
                            Id = 41,
                            Correta = true,
                            Letra = "A",
                            PerguntaId = 11,
                            Texto = "Reisado"
                        },
                        new
                        {
                            Id = 42,
                            Correta = false,
                            Letra = "B",
                            PerguntaId = 11,
                            Texto = "Chegança"
                        },
                        new
                        {
                            Id = 43,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 11,
                            Texto = "Lambe-Sujos"
                        },
                        new
                        {
                            Id = 44,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 11,
                            Texto = "Cacumbi"
                        },
                        new
                        {
                            Id = 45,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 12,
                            Texto = "Acarajé"
                        },
                        new
                        {
                            Id = 46,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 12,
                            Texto = "Amendoim cozido"
                        },
                        new
                        {
                            Id = 47,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 12,
                            Texto = "Macaxeira"
                        },
                        new
                        {
                            Id = 48,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 12,
                            Texto = "Milho assado"
                        },
                        new
                        {
                            Id = 49,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 13,
                            Texto = "Rio Mar"
                        },
                        new
                        {
                            Id = 50,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 13,
                            Texto = "Velho Chico"
                        },
                        new
                        {
                            Id = 51,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 13,
                            Texto = "Rio das Garças"
                        },
                        new
                        {
                            Id = 52,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 13,
                            Texto = "Opará (embora seja o nome indígena, o apelido carinhoso popular é Velho Chico)"
                        },
                        new
                        {
                            Id = 53,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 14,
                            Texto = "Mercado Albano Franco"
                        },
                        new
                        {
                            Id = 54,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 14,
                            Texto = "Mercado Thales Ferraz"
                        },
                        new
                        {
                            Id = 55,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 14,
                            Texto = "Mercado da Piçarra"
                        },
                        new
                        {
                            Id = 56,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 14,
                            Texto = "Mercado de Itabaiana"
                        },
                        new
                        {
                            Id = 57,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 15,
                            Texto = "Bolo de Milho"
                        },
                        new
                        {
                            Id = 58,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 15,
                            Texto = "Pé de Moleque Sergipano"
                        },
                        new
                        {
                            Id = 59,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 15,
                            Texto = "Canjica"
                        },
                        new
                        {
                            Id = 60,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 15,
                            Texto = "Pamonha"
                        },
                        new
                        {
                            Id = 61,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 16,
                            Texto = "Graviola"
                        },
                        new
                        {
                            Id = 62,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 16,
                            Texto = "Mangaba"
                        },
                        new
                        {
                            Id = 63,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 16,
                            Texto = "Pitomba"
                        },
                        new
                        {
                            Id = 64,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 16,
                            Texto = "Seriguela"
                        },
                        new
                        {
                            Id = 65,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 17,
                            Texto = "Repente"
                        },
                        new
                        {
                            Id = 66,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 17,
                            Texto = "Cordel"
                        },
                        new
                        {
                            Id = 67,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 17,
                            Texto = "Soneto"
                        },
                        new
                        {
                            Id = 68,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 17,
                            Texto = "Crônica"
                        },
                        new
                        {
                            Id = 69,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 18,
                            Texto = "Lambe-Sujos"
                        },
                        new
                        {
                            Id = 70,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 18,
                            Texto = "Caboclinhos"
                        },
                        new
                        {
                            Id = 71,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 18,
                            Texto = "Taieira"
                        },
                        new
                        {
                            Id = 72,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 18,
                            Texto = "Cacumbi"
                        },
                        new
                        {
                            Id = 73,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 19,
                            Texto = "Dadá"
                        },
                        new
                        {
                            Id = 74,
                            Correta = false,
                            Letra = "B",
                            PerguntaId = 19,
                            Texto = "Enedina"
                        },
                        new
                        {
                            Id = 75,
                            Correta = true,
                            Letra = "C",
                            PerguntaId = 19,
                            Texto = "Maria Bonita"
                        },
                        new
                        {
                            Id = 76,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 19,
                            Texto = "Maria Feliciana"
                        },
                        new
                        {
                            Id = 77,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 20,
                            Texto = "Estância"
                        },
                        new
                        {
                            Id = 78,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 20,
                            Texto = "Itabaiana"
                        },
                        new
                        {
                            Id = 79,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 20,
                            Texto = "Propriá"
                        },
                        new
                        {
                            Id = 80,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 20,
                            Texto = "Lagarto"
                        },
                        new
                        {
                            Id = 81,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 21,
                            Texto = "Mastruz com Leite"
                        },
                        new
                        {
                            Id = 82,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 21,
                            Texto = "Calcinha Preta"
                        },
                        new
                        {
                            Id = 83,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 21,
                            Texto = "Cavaleiros do Forró"
                        },
                        new
                        {
                            Id = 84,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 21,
                            Texto = "Magníficos"
                        },
                        new
                        {
                            Id = 85,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 22,
                            Texto = "12 de outubro"
                        },
                        new
                        {
                            Id = 86,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 22,
                            Texto = "24 de outubro"
                        },
                        new
                        {
                            Id = 87,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 22,
                            Texto = "17 de março"
                        },
                        new
                        {
                            Id = 88,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 22,
                            Texto = "08 de julho"
                        },
                        new
                        {
                            Id = 89,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 23,
                            Texto = "Tinta guache"
                        },
                        new
                        {
                            Id = 90,
                            Correta = false,
                            Letra = "B",
                            PerguntaId = 23,
                            Texto = "Lama de mangue"
                        },
                        new
                        {
                            Id = 91,
                            Correta = true,
                            Letra = "C",
                            PerguntaId = 23,
                            Texto = "Pó de fuligem (carvão)"
                        },
                        new
                        {
                            Id = 92,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 23,
                            Texto = "Graxa de sapato"
                        },
                        new
                        {
                            Id = 93,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 24,
                            Texto = "Amorosa"
                        },
                        new
                        {
                            Id = 94,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 24,
                            Texto = "Clemilda"
                        },
                        new
                        {
                            Id = 95,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 24,
                            Texto = "Paulinha Abelha"
                        },
                        new
                        {
                            Id = 96,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 24,
                            Texto = "Maysa"
                        },
                        new
                        {
                            Id = 97,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 25,
                            Texto = "São João"
                        },
                        new
                        {
                            Id = 98,
                            Correta = false,
                            Letra = "B",
                            PerguntaId = 25,
                            Texto = "Santo Antônio"
                        },
                        new
                        {
                            Id = 99,
                            Correta = true,
                            Letra = "C",
                            PerguntaId = 25,
                            Texto = "Reis Magos"
                        },
                        new
                        {
                            Id = 100,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 25,
                            Texto = "São Pedro"
                        },
                        new
                        {
                            Id = 101,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 26,
                            Texto = "Itabaiana"
                        },
                        new
                        {
                            Id = 102,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 26,
                            Texto = "Santana do São Francisco"
                        },
                        new
                        {
                            Id = 103,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 26,
                            Texto = "Umbaúba"
                        },
                        new
                        {
                            Id = 104,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 26,
                            Texto = "Simão Dias"
                        },
                        new
                        {
                            Id = 105,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 27,
                            Texto = "Centro"
                        },
                        new
                        {
                            Id = 106,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 27,
                            Texto = "Atalaia"
                        },
                        new
                        {
                            Id = 107,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 27,
                            Texto = "Jardins"
                        },
                        new
                        {
                            Id = 108,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 27,
                            Texto = "Bairro Industrial"
                        },
                        new
                        {
                            Id = 109,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 28,
                            Texto = "Queima do Judas"
                        },
                        new
                        {
                            Id = 110,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 28,
                            Texto = "Festa do Mastro"
                        },
                        new
                        {
                            Id = 111,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 28,
                            Texto = "Casamento Caipira"
                        },
                        new
                        {
                            Id = 112,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 28,
                            Texto = "Batalha de Buscapés"
                        },
                        new
                        {
                            Id = 113,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 29,
                            Texto = "Forró Caju"
                        },
                        new
                        {
                            Id = 114,
                            Correta = true,
                            Letra = "B",
                            PerguntaId = 29,
                            Texto = "FASC (Festival de Artes de São Cristóvão)"
                        },
                        new
                        {
                            Id = 115,
                            Correta = false,
                            Letra = "C",
                            PerguntaId = 29,
                            Texto = "Verão Sergipe"
                        },
                        new
                        {
                            Id = 116,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 29,
                            Texto = "Festa do Mastro"
                        },
                        new
                        {
                            Id = 117,
                            Correta = false,
                            Letra = "A",
                            PerguntaId = 30,
                            Texto = "Axé"
                        },
                        new
                        {
                            Id = 118,
                            Correta = false,
                            Letra = "B",
                            PerguntaId = 30,
                            Texto = "Samba"
                        },
                        new
                        {
                            Id = 119,
                            Correta = true,
                            Letra = "C",
                            PerguntaId = 30,
                            Texto = "Forró"
                        },
                        new
                        {
                            Id = 120,
                            Correta = false,
                            Letra = "D",
                            PerguntaId = 30,
                            Texto = "Pagode"
                        });
                });

            modelBuilder.Entity("quizsergipe_api.Models.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Perguntas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enunciado = "Qual manifestação folclórica de Laranjeiras utiliza melaço de cana para pintar o corpo dos participantes que representam escravizados fugidos?"
                        },
                        new
                        {
                            Id = 2,
                            Enunciado = "Como é chamada a figura histórica que media 2,25 metros e é considerada a mulher mais alta de Sergipe?"
                        },
                        new
                        {
                            Id = 3,
                            Enunciado = "Quem era o prático que atravessava a barra do Rio Sergipe a nado para guiar as embarcações?"
                        },
                        new
                        {
                            Id = 4,
                            Enunciado = "Qual é o artefato de pirotecnia artesanal que corre num arame e é o maior símbolo de Estância?"
                        },
                        new
                        {
                            Id = 5,
                            Enunciado = "Qual apelido carinhoso Sergipe recebe durante o mês de junho pela animação das suas festas?"
                        },
                        new
                        {
                            Id = 6,
                            Enunciado = "Qual crustáceo é servido tradicionalmente com pirão e vinagrete na Orla da Atalaia?"
                        },
                        new
                        {
                            Id = 7,
                            Enunciado = "Qual fruto é tão importante que o nome da capital, Aracaju, deriva de um termo indígena ligado a ele?"
                        },
                        new
                        {
                            Id = 8,
                            Enunciado = "Qual cidade sergipana é a 4ª mais antiga do Brasil e possui uma praça que é Patrimônio da Humanidade?"
                        },
                        new
                        {
                            Id = 9,
                            Enunciado = "Qual movimento social do sertão teve seu fim trágico na Grota de Angicos, em território sergipano?"
                        },
                        new
                        {
                            Id = 10,
                            Enunciado = "Qual grupo folclórico utiliza armas longas (carregadas com pólvora seca) para saudar santos e autoridades?"
                        },
                        new
                        {
                            Id = 11,
                            Enunciado = "Qual grupo folclórico usa trajes espelhados e chapéus em forma de castelo para celebrar o Dia de Reis?"
                        },
                        new
                        {
                            Id = 12,
                            Enunciado = "Qual petisco, geralmente vendido cozido em carrinhos, é considerado Patrimônio Imaterial de Sergipe?"
                        },
                        new
                        {
                            Id = 13,
                            Enunciado = "Como o Rio São Francisco é carinhosamente chamado pela população ribeirinha de Sergipe?"
                        },
                        new
                        {
                            Id = 14,
                            Enunciado = "Qual mercado central de Aracaju é famoso pela venda de artesanato, rendas e artigos de palha?"
                        },
                        new
                        {
                            Id = 15,
                            Enunciado = "Qual iguaria junina é feita de massa de puba (mandioca fermentada), coco e açúcar, assada tradicionalmente no forno a lenha?"
                        },
                        new
                        {
                            Id = 16,
                            Enunciado = "Qual fruto silvestre é considerado o fruto símbolo de Sergipe e é base de sorvetes e doces amados localmente?"
                        },
                        new
                        {
                            Id = 17,
                            Enunciado = "Como se chama o gênero literário popular, escrito em versos rimados e métrica rígida, que tradicionalmente é impresso em pequenos folhetos e exposto em cordas nas feiras?"
                        },
                        new
                        {
                            Id = 18,
                            Enunciado = "Na tradicional festa de Laranjeiras, qual grupo representa os indígenas catequizados e usa cocares de penas?"
                        },
                        new
                        {
                            Id = 19,
                            Enunciado = "Quem foi a primeira mulher a entrar oficialmente para o bando de Lampião, tornando-se Rainha do Cangaço?"
                        },
                        new
                        {
                            Id = 20,
                            Enunciado = "Qual cidade sergipana é conhecida como a \"Capital do Caminhão\" e maior centro de castanha de caju?"
                        },
                        new
                        {
                            Id = 21,
                            Enunciado = "Qual banda de Aracaju conquistou o Brasil nos anos 2000 com o \"Forró Eletrônico\" e tinha Paulinha Abelha como uma de suas estrelas?"
                        },
                        new
                        {
                            Id = 22,
                            Enunciado = "Em qual data de outubro comemora-se oficialmente o Dia da Sergipanidade?"
                        },
                        new
                        {
                            Id = 23,
                            Enunciado = "Qual material é misturado ao melaço de cana para dar a cor preta à pele dos participantes dos Lambe-Sujos?"
                        },
                        new
                        {
                            Id = 24,
                            Enunciado = "Qual cantora sergipana é conhecida como a \"Rainha do Forró\" e imortalizou o sucesso \"Prenda o Tadeu\"?"
                        },
                        new
                        {
                            Id = 25,
                            Enunciado = "Qual das figuras bíblicas abaixo é a grande homenageada nas festas de Reisado em Sergipe?"
                        },
                        new
                        {
                            Id = 26,
                            Enunciado = "Qual cidade sergipana é famosa pela produção de cerâmica artesanal, especialmente as \"bonecas\" de barro?"
                        },
                        new
                        {
                            Id = 27,
                            Enunciado = "Qual é o bairro de Aracaju onde se localiza a famosa \"Passarela do Caranguejo\"?"
                        },
                        new
                        {
                            Id = 28,
                            Enunciado = "Como é chamado o ritual junino de Capela que envolve a busca por uma árvore na mata para ser plantada no centro da cidade?"
                        },
                        new
                        {
                            Id = 29,
                            Enunciado = "Como é chamado o maior evento de arte e cultura que ocorre anualmente na cidade de São Cristóvão?"
                        },
                        new
                        {
                            Id = 30,
                            Enunciado = "Qual o ritmo musical que define a identidade de Sergipe como o \"País do Forró\"?"
                        });
                });

            modelBuilder.Entity("quizsergipe_api.Models.QuizSessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PontuacaoFinal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QuizSessoes", (string)null);
                });

            modelBuilder.Entity("quizsergipe_api.Models.QuizSessaoPergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizSessaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaId");

                    b.HasIndex("QuizSessaoId", "Ordem")
                        .IsUnique();

                    b.HasIndex("QuizSessaoId", "PerguntaId")
                        .IsUnique();

                    b.ToTable("QuizSessaoPerguntas", (string)null);
                });

            modelBuilder.Entity("quizsergipe_api.Models.RespostaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean");

                    b.Property<int>("AlternativaId")
                        .HasColumnType("integer");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizSessaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RespondidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlternativaId");

                    b.HasIndex("PerguntaId");

                    b.HasIndex("QuizSessaoId", "PerguntaId")
                        .IsUnique();

                    b.ToTable("RespostasUsuario", (string)null);
                });

            modelBuilder.Entity("quizsergipe_api.Models.Alternativa", b =>
                {
                    b.HasOne("quizsergipe_api.Models.Pergunta", "Pergunta")
                        .WithMany("Alternativas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("quizsergipe_api.Models.QuizSessaoPergunta", b =>
                {
                    b.HasOne("quizsergipe_api.Models.Pergunta", "Pergunta")
                        .WithMany()
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("quizsergipe_api.Models.QuizSessao", "QuizSessao")
                        .WithMany("Perguntas")
                        .HasForeignKey("QuizSessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");

                    b.Navigation("QuizSessao");
                });

            modelBuilder.Entity("quizsergipe_api.Models.RespostaUsuario", b =>
                {
                    b.HasOne("quizsergipe_api.Models.Alternativa", "Alternativa")
                        .WithMany()
                        .HasForeignKey("AlternativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("quizsergipe_api.Models.Pergunta", "Pergunta")
                        .WithMany()
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("quizsergipe_api.Models.QuizSessao", "QuizSessao")
                        .WithMany("Respostas")
                        .HasForeignKey("QuizSessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alternativa");

                    b.Navigation("Pergunta");

                    b.Navigation("QuizSessao");
                });

            modelBuilder.Entity("quizsergipe_api.Models.Pergunta", b =>
                {
                    b.Navigation("Alternativas");
                });

            modelBuilder.Entity("quizsergipe_api.Models.QuizSessao", b =>
                {
                    b.Navigation("Perguntas");

                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
